#!/bin/bash

USING_PYTHON=$(dirname $0)/using-python
if [[ -f $USING_PYTHON ]]
then
    BUILD_DIR=$(dirname $0)/build
    export PYTHONPATH=$BUILD_DIR:$PYTHONPATH
    python3 python/compiler.py $1 > $2
else
    java -cp "$CLASSPATH:classes" Compiler $1 > $2
fi

